# Site
repository: leopulous/leopulous.github.io
favicon: images/favicon.ico

# Personal info
name: Thu Lam Nguyen
title: Undergraduate Sofware Development Student
email: nguyenl9@myumanitoba.ca
website: https://leopulous.github.io/

# Social links
github_username:  https://github.com/leopulous
linkedin_username: www.linkedin.com/in/liamnguyenn98

# About Section
# about_title: About Me
about_profile_image: images/avatar.png
about_content: |
  Hello! My name is Lam. I'm currently a third year Computer Science student with passion for coding.
  I love designing and develop innovative applications that stimulates my curiosity and at the same time improve my programming skills. 
  I enjoy interacting with people, spread ideas and exchange views to help each other improve. 
  
 
  My favorite programming quote is: 
  "Every great developer you know got there by solving problems they were unqualified to solve until they actually did it." -Patrick McKenzie
 
  My specialties programming languages are:
  <mark>Java</mark>,
  <mark>Python</mark>,
  <mark>SQL</mark>,
  <mark>C++</mark>,
  <mark>C</mark>,
  <mark>Ruby</mark>,
  <mark>HTML</mark>,
  <mark>CSS</mark>.

  Tools that I am familiar with:
  <mark>Git</mark>,
  <mark>Pycharm</mark>,
  <mark>Intellij</mark>,
  <mark>Visual Studio Code</mark>,
  <mark>RubyMine</mark>,
  <mark>CLion</mark>.

  
  Frameworks and Libraries:
  <mark>PyGame</mark>,
  <mark>matplotlib</mark>,
  <mark>Intellij</mark>,
  <mark>Bootstrap</mark>,
  <mark>Flask</mark>,
  <mark>JDBC</mark>.

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
more_title: What I bring to the table
more_content: |
  Programming consists of many layers. It's not all day coding and problem solving. Soft skill is also an important part to a successful
  developer. I've spent a good amount of my time studying the art of effective working. I usually read articles and discussions threads 
  online with the aim to investigate and incorporate the views of programming students and tech leaders on their personal experiences to
  develop a more efficient technique to deal with a problem head-on. This works well with my assignment agenda and personal projects.

  I'm a realistic and goal-oriented individual. I value hard work and effort, which makes them my working style. When approaching a 
  difficult dilemma, I would take an overall look at the problem and break it down into parts. I believe that a throughout understanding
  of the structure gives me a better vision at all the possibilities that I can do.

  Finally, I value team work and collaborations. As much as I admire and respect other people, I love to hear other people's ideas and 
  visions. I believe that by encouraging developers to voice themselves, there are many valuable ideas that comes with it. At the end of
  the day, the product is meant to reflect on the heart and soul of the entire group. By sharing the same goal across the team, we can 
  develop something that speaks volume to the community.

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

# sass:
#   style: compressed
