# Site
repository: leopulous/leopulous.github.io
favicon: images/favicon.ico

# Personal info
name: Thu Lam Nguyen
title: Undergraduate Sofware Development Student
email: nguyenl9@myumanitoba.ca
website: https://leopulous.github.io/

# Social links
github_username:  https://github.com/leopulous
linkedin_username: www.linkedin.com/in/liamnguyenn98

# About Section
# about_title: About Me
about_profile_image: images/avatar.png
about_content: |
  Hello! My name is Lam. I'm currently a third year Computer Science student with passion for coding.
  I love designing and develop innovative applications that stimulates my curiosity and at the same time improve my programming skills.
  I enjoy interacting with people, spread ideas and exchange views to help each other improve.
  My favorite programming quote is:
  "Every great developer you know got there by solving problems they were unqualified to solve until they actually did it."
  - Patrick McKenzie
  My specialties are
  <mark>Java</mark>,
  <mark>Python</mark>,
  <mark>SQL</mark>,
  <mark>C++</mark>,
  <mark>C</mark>,
  <mark>Ruby</mark>,
  <mark>HTML</mark>,
  <mark>CSS</mark>.

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
more_title: When I'm Not Programming
more_content: |
  When I'm not sat at my desk I am very active and spend most of my time outdoors. I do a lot a sports such as
  mountain biking, road cycling, kitesuring and landboarding as well as trying to make time for things like
  rock climbing and playing some rugby. Since my time at Uni I have become a very keen Kitesurfer and freestyle
  Landboarder. In 2014 I competed and won the amateur landboard British powerkite tour.

  I'm interested in photography and videography as I like to be creative, this is mainly through sport but
  I enjoy landscape and abstract photography too. I like to showcase my work on my website and instagram if
  you would like to take a look -
  [jwgmedia.co.uk](http://jwgmedia.co.uk/) / [jameswgrant](https://www.instagram.com/jameswgrant/).

  Finally during the rest of my free time you will either find me working on my bikes, rock climbing at one of
  Bristol's indoor climbing centres or down the Rec supporting Bath Rugby.

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

# sass:
#   style: compressed
